colours = tribble(
  ~PartyAb,      ~Name,                                                          ~PartyColour,
  "AJP",         "Animal Justice Party",                                            "#A52A2A",
  "ALP",         "Labor Party",                                                     "#F00011",
  "ALP",         "Labor Party",                                                     "#F00011",
  "ALP",         "Labor Party",                                                     "#F00011",
  "ASP",         "Shooters, Fishers and Farmers Party",                             "#E52B50",
  "AUC",         "Australian Christians",                                           "#ffdc00",
  "AUD",         "Australian Democrats",                                            "#ffdc00",
  "AUP",         "Australian Progressives",                                         "#4B0082",
  "AUVA",        "Australian Values Party",                                         "#BDAF77",
  "CEC",         "Citizens Party",                                                  "#666600",
  "CLP",         "NT CLP",                                                          "#FF7F00",
  "CYA",         "Australian Federation Party",                                     "#E3A02D",
  "DHJP",        "Derryn Hinch's Justice Party",                                    "#002F5D",
  "DPDA",        "Democratic Alliance",                                             "#4BBEAB",
  "DPDA",        "Drew Pavlou Democratic Alliance",                                 "#4BBEAB",
  "GAP",         "The Great Australian Party",                                      "#142961",
  "GRN",         "Queensland Greens",                                               "#10C25B",
  "GRN",         "The Greens",                                                      "#10C25B",
  "GRN",         "The Greens",                                                      "#10C25B",
  "GVIC",        "The Greens",                                                      "#10C25B",
  "HMP",         "Legalise Cannabis Australia",                                     "#72C342",
  "IAP",         "Indigenous - Aboriginal Party of Australia",                      "#CC7722",
  "IMO",         "Informed Medical Options Party",                                  "#DD7D1D",
  "IND",         "Independent",                                                     "#888888",
  "JLN",         "Jacqui Lambie Network",                                           "#FFCB08",
  "KAP",         "Katter's Australian Party (KAP)",                                 "#B50204",
  "LDP",         "Liberal Democrats",                                               "#fec327",
  "LNP",         "Liberal National Party",                                          "#1456F1",
  "LP",          "Liberal Party",                                                   "#1456F1",
  "NP",          "The Nationals",                                                   "#008000",
  "NP",          "The Nationals",                                                   "#008000",
  "ON",          "Pauline Hanson's One Nation",                                     "#f36c21",
  "REAS",        "Reason Australia",                                                "#4BB8B3",
  "SAL",         "Socialist Alliance",                                              "#990000",
  "SOPA",        "FUSION: Science, Pirate, Secular, Climate Emergency",             "#C926F2",
  "SPP",         "Sustainable Australia Party - Stop Overdevelopment / Corruption", "#047E49",
  "TLOC",        "The Local Party",                                                 "#0081C8",
  "TNL",         "TNL",                                                             "#54C2BD",
  "UAPP",        "United Australia Party",                                          "#00008B",
  "VNS",         "Victorian Socialists",                                            "#000000",
  "WAP",         "WESTERN AUSTRALIA PARTY",                                         "#000000",
  "XEN",         "Centre Alliance",                                                 "#ff6300"
)

colourScale = fn.df_to_scale(colours, "PartyAb", "PartyColour")